// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlatformId } from "./PlatformId";

export interface GenericAccount { id: PlatformId, pfpUrl: string, displayName: string, }