// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlatformType } from "./PlatformType";

export type PlatformId = [PlatformType, string];