on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # See https://yarnpkg.com/features/zero-installs#does-it-have-security-implications
      - run: yarn install --immutable --immutable-cache --check-cache
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --immutable --immutable-cache && yarn build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --immutable --immutable-cache && yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --immutable --immutable-cache && xvfb-run yarn test --no-watch --no-progress --browsers Chrome
