name: UI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main


jobs:
  check-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      # See https://yarnpkg.com/features/zero-installs#does-it-have-security-implications
      - run: yarn install --immutable --immutable-cache --check-cache
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn install --immutable --immutable-cache
      - run: yarn build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn install --immutable --immutable-cache
      - run: yarn lint
  test:
    permissions:
      actions: write
      pull-requests: write
      statuses: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn install --immutable --immutable-cache
      - name: Test
        run: xvfb-run yarn test --no-watch --no-progress --browsers Chrome
      - name: Create coverage report
        uses: clearlyip/code-coverage-report-action@v1
        if: ${{ ! cancelled()  }}
        id: code_coverage_report_action
        with:
          filename: 'dist/coverage-ui/cobertura-coverage.xml'
          fail_on_negative_difference: true
          artifact_download_workflow_names: 'UI'
          overall_coverage_fail_threshold: 50
          badge: true
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.code_coverage_report_action.outputs.file != '' && github.event_name == 'pull_request' && (success() || failure())
        with:
          recreate: true
          path: code-coverage-results.md
